version: "3.9"

services:
  my-nginx-image:
    build:
      context: .
      secrets:
        - user1_password
        - user2_password
        - user3_password
        - private_user_password
      args:
        progress: plain
    ports:
      - "80:8080"
      - "443:4443"
      - "2222:22"
    cap_drop:
      - all
    cap_add:
      - chown
      - dac_override
      - setgid
      - setuid
      - net_bind_service
    # read_only: true
    security_opt:
      # - "seccomp=./seccomp-profile.json"
      - "no-new-privileges:true"  # Prevent privilege escalation
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      # restart_policy:
      #   condition: on-failure

      
secrets:
  user1_password:
    file: ./.secrets/user1_password.txt
  user2_password:
    file: ./.secrets/user2_password.txt
  user3_password:
    file: ./.secrets/user3_password.txt
  private_user_password:
    file: ./.secrets/private_user_password.txt

             